project_id = "udpldrrpebdyuiqdtqnq"

[functions.calendar-events]
verify_jwt = false

[functions.chat-with-ai]
verify_jwt = false

[functions.chat-operations]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.demo-chat]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-ai-image]
verify_jwt = false

[functions.chapter-request-email]
verify_jwt = false
