import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.50.3";
import * as zip from "https://deno.land/x/zipjs@v2.7.34/index.js";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

// Text file extensions we can read from ZIPs
const TEXT_EXTENSIONS = new Set([
  "xml", "lua", "txt", "json", "cfg", "ini", "csv", "md",
  "html", "css", "js", "i3d", "shader", "material", "grle",
  "l10n", "log", "yaml", "yml",
]);

// FS mod templates
const FS_TEMPLATES: Record<string, Record<string, string>> = {
  script: {
    "modDesc.xml": `<?xml version="1.0" encoding="utf-8" standalone="no"?>
<modDesc descVersion="80">
  <author>CriderGPT</author>
  <version>1.0.0.0</version>
  <title>
    <en>{{MOD_NAME}}</en>
  </title>
  <description>
    <en>{{MOD_DESC}}</en>
  </description>
  <iconFilename>icon.dds</iconFilename>
  <multiplayer supported="true"/>
  <extraSourceFiles>
    <sourceFile filename="scripts/main.lua"/>
  </extraSourceFiles>
</modDesc>`,
    "scripts/main.lua": `-- {{MOD_NAME}}
-- Generated by CriderGPT

{{MOD_NAME}} = {}
{{MOD_NAME}}.modDirectory = g_currentModDirectory

function {{MOD_NAME}}:loadMap(name)
    print("{{MOD_NAME}} loaded!")
end

function {{MOD_NAME}}:update(dt)
    -- Update logic here
end

addModEventListener({{MOD_NAME}})
`,
  },
  placeable: {
    "modDesc.xml": `<?xml version="1.0" encoding="utf-8" standalone="no"?>
<modDesc descVersion="80">
  <author>CriderGPT</author>
  <version>1.0.0.0</version>
  <title>
    <en>{{MOD_NAME}}</en>
  </title>
  <description>
    <en>{{MOD_DESC}}</en>
  </description>
  <iconFilename>icon.dds</iconFilename>
  <multiplayer supported="true"/>
  <placeableTypes>
    <type name="{{MOD_NAME_SAFE}}" className="Placeable" filename="$dataS/scripts/placeables/Placeable.lua"/>
  </placeableTypes>
  <placeables>
    <placeable typeName="{{MOD_NAME_SAFE}}" xmlFilename="placeable.xml"/>
  </placeables>
</modDesc>`,
    "placeable.xml": `<?xml version="1.0" encoding="utf-8" standalone="no"?>
<placeable>
  <base>
    <filename>placeable.i3d</filename>
  </base>
  <placement sizeX="5" sizeZ="5" testSizeX="5" testSizeZ="5"/>
</placeable>`,
  },
  fillType: {
    "modDesc.xml": `<?xml version="1.0" encoding="utf-8" standalone="no"?>
<modDesc descVersion="80">
  <author>CriderGPT</author>
  <version>1.0.0.0</version>
  <title>
    <en>{{MOD_NAME}}</en>
  </title>
  <description>
    <en>{{MOD_DESC}}</en>
  </description>
  <iconFilename>icon.dds</iconFilename>
  <multiplayer supported="true"/>
  <fillTypes>
    <type name="{{FILL_TYPE_NAME}}" title="{{MOD_NAME}}" showOnPriceTable="true" unitShort="$l10n_unit_literShort">
      <economy pricePerLiter="1.5"/>
    </type>
  </fillTypes>
</modDesc>`,
  },
};

// ===================== READ ZIP =====================
async function readZip(base64Data: string): Promise<{ fileTree: string[]; files: Record<string, string>; summary: string }> {
  // Strip data URL prefix if present
  const raw = base64Data.includes(",") ? base64Data.split(",")[1] : base64Data;
  const binaryStr = atob(raw);
  const bytes = new Uint8Array(binaryStr.length);
  for (let i = 0; i < binaryStr.length; i++) bytes[i] = binaryStr.charCodeAt(i);

  const blob = new Blob([bytes]);
  const reader = new zip.ZipReader(new zip.BlobReader(blob));
  const entries = await reader.getEntries();

  const fileTree: string[] = [];
  const files: Record<string, string> = {};
  let totalSize = 0;
  let textFileCount = 0;
  let binaryFileCount = 0;

  for (const entry of entries) {
    fileTree.push(entry.filename);

    if (entry.directory) continue;

    const ext = entry.filename.split(".").pop()?.toLowerCase() || "";
    totalSize += entry.uncompressedSize || 0;

    if (TEXT_EXTENSIONS.has(ext) && (entry.uncompressedSize || 0) < 500_000) {
      // Read text files
      if (entry.getData) {
        const writer = new zip.TextWriter();
        const content = await entry.getData(writer);
        files[entry.filename] = content;
        textFileCount++;
      }
    } else {
      binaryFileCount++;
      files[entry.filename] = `[Binary file: ${ext}, ${((entry.uncompressedSize || 0) / 1024).toFixed(1)}KB]`;
    }
  }

  await reader.close();

  // Detect FS mod
  const hasModDesc = fileTree.some(f => f.toLowerCase().includes("moddesc.xml"));
  const hasLua = fileTree.some(f => f.endsWith(".lua"));
  const hasI3d = fileTree.some(f => f.endsWith(".i3d"));

  let modType = "Unknown";
  if (hasModDesc) {
    if (hasLua && hasI3d) modType = "Full FS Mod (scripts + 3D)";
    else if (hasLua) modType = "FS Script Mod";
    else if (hasI3d) modType = "FS 3D/Map Mod";
    else modType = "FS Mod (XML-based)";
  }

  const summary = [
    `📦 **ZIP Analysis**`,
    `- **Files**: ${entries.length} total (${textFileCount} text, ${binaryFileCount} binary)`,
    `- **Size**: ${(totalSize / 1024).toFixed(1)} KB uncompressed`,
    `- **Detected Type**: ${modType}`,
    hasModDesc ? "- ✅ modDesc.xml found" : "- ⚠️ No modDesc.xml — may not be a valid FS mod",
    hasLua ? "- ✅ LUA scripts found" : "",
    hasI3d ? "- ✅ I3D models found" : "",
  ].filter(Boolean).join("\n");

  return { fileTree, files, summary };
}

// ===================== CREATE ZIP =====================
async function createZip(
  files: Array<{ path: string; content: string }>,
  modName: string,
  userId: string,
): Promise<{ downloadUrl: string; fileName: string }> {
  const blobWriter = new zip.BlobWriter("application/zip");
  const writer = new zip.ZipWriter(blobWriter);

  for (const file of files) {
    await writer.add(file.path, new zip.TextReader(file.content));
  }

  await writer.close();
  const blob = await blobWriter.getData();

  // Upload to Supabase Storage
  const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
  const safeName = modName.replace(/[^a-zA-Z0-9_-]/g, "_");
  const fileName = `${safeName}_${Date.now()}.zip`;
  const storagePath = `${userId}/mods/${fileName}`;

  const arrayBuffer = await blob.arrayBuffer();
  const uint8 = new Uint8Array(arrayBuffer);

  const { error: uploadError } = await supabase.storage
    .from("user-files")
    .upload(storagePath, uint8, {
      contentType: "application/zip",
      upsert: true,
    });

  if (uploadError) throw new Error(`Upload failed: ${uploadError.message}`);

  // Get signed URL (1 hour)
  const { data: signedData, error: signedError } = await supabase.storage
    .from("user-files")
    .createSignedUrl(storagePath, 3600);

  if (signedError) throw new Error(`Signed URL failed: ${signedError.message}`);

  return { downloadUrl: signedData.signedUrl, fileName };
}

// ===================== MAIN HANDLER =====================
serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const body = await req.json();
    const { mode, user_id } = body;

    if (mode === "read") {
      const { zip_base64 } = body;
      if (!zip_base64) {
        return new Response(JSON.stringify({ error: "Missing zip_base64" }), {
          status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }

      const result = await readZip(zip_base64);
      return new Response(JSON.stringify(result), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    if (mode === "create") {
      const { files, mod_name, template, template_vars } = body;

      let filesToZip: Array<{ path: string; content: string }> = [];

      if (template && FS_TEMPLATES[template]) {
        // Use a template
        const vars = template_vars || {};
        const modNameSafe = (vars.mod_name || mod_name || "MyMod").replace(/\s+/g, "");
        const replacements: Record<string, string> = {
          "{{MOD_NAME}}": vars.mod_name || mod_name || "MyMod",
          "{{MOD_NAME_SAFE}}": modNameSafe,
          "{{MOD_DESC}}": vars.mod_desc || "Generated by CriderGPT",
          "{{FILL_TYPE_NAME}}": vars.fill_type_name || modNameSafe.toUpperCase(),
        };

        for (const [path, content] of Object.entries(FS_TEMPLATES[template])) {
          let processed = content;
          for (const [key, val] of Object.entries(replacements)) {
            processed = processed.replaceAll(key, val);
          }
          filesToZip.push({ path, content: processed });
        }
      }

      // Add/override with custom files
      if (files?.length) {
        for (const f of files) {
          const existingIdx = filesToZip.findIndex((e) => e.path === f.path);
          if (existingIdx >= 0) filesToZip[existingIdx] = f;
          else filesToZip.push(f);
        }
      }

      if (!filesToZip.length) {
        return new Response(JSON.stringify({ error: "No files to package" }), {
          status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }

      const result = await createZip(filesToZip, mod_name || "CriderGPT_Mod", user_id || "anonymous");
      return new Response(JSON.stringify({
        success: true,
        download_url: result.downloadUrl,
        file_name: result.fileName,
        files_count: filesToZip.length,
        file_list: filesToZip.map((f) => f.path),
      }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    return new Response(JSON.stringify({ error: "Invalid mode. Use 'read' or 'create'" }), {
      status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error: any) {
    console.error("process-mod-zip error:", error);
    return new Response(JSON.stringify({ error: error.message || "Processing failed" }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
