import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { Plus, FolderOpen, Rocket, Clock, CheckCircle, Loader2 } from "lucide-react";

interface Project {
  id: number;
  name: string;
  status: 'active' | 'completed' | 'pending';
  progress: number;
  type: 'fs22-mod' | 'fs25-mod' | 'api-integration' | 'automation';
  lastUpdated: Date;
}

export function ProjectManager() {
  const [projects, setProjects] = useState<Project[]>([]);
  const [loading, setLoading] = useState(true);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [newProject, setNewProject] = useState({
    name: '',
    type: 'api-integration' as Project['type'],
    status: 'pending' as Project['status']
  });
  const { user } = useAuth();
  const { toast } = useToast();

  useEffect(() => {
    loadProjects();
  }, [user]);

  const loadProjects = async () => {
    if (!user) return;
    
    try {
      setLoading(true);
      // For now, using mock data since we don't have a projects table
      // In a real implementation, you'd fetch from Supabase
      setProjects([
        {
          id: 1,
          name: "FS25 Harvester Mod",
          status: 'active',
          progress: 75,
          type: 'fs25-mod',
          lastUpdated: new Date('2024-01-15')
        },
        {
          id: 2,
          name: "SMS Auto-Response System",
          status: 'completed',
          progress: 100,
          type: 'automation',
          lastUpdated: new Date('2024-01-10')
        },
        {
          id: 3,
          name: "Weather API Integration",
          status: 'pending',
          progress: 25,
          type: 'api-integration',
          lastUpdated: new Date('2024-01-12')
        }
      ]);
    } catch (error) {
      console.error('Error loading projects:', error);
      toast({
        title: "Error",
        description: "Failed to load projects",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const handleCreateProject = async () => {
    if (!newProject.name.trim()) {
      toast({
        title: "Error",
        description: "Project name is required",
        variant: "destructive",
      });
      return;
    }

    try {
      const project: Project = {
        id: Date.now(), // In real app, this would be generated by the database
        name: newProject.name,
        status: newProject.status,
        progress: 0,
        type: newProject.type,
        lastUpdated: new Date()
      };

      setProjects(prev => [project, ...prev]);
      setDialogOpen(false);
      setNewProject({ name: '', type: 'api-integration', status: 'pending' });
      
      toast({
        title: "Success",
        description: "Project created successfully",
      });
    } catch (error) {
      console.error('Error creating project:', error);
      toast({
        title: "Error",
        description: "Failed to create project",
        variant: "destructive",
      });
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'active': return 'bg-cyber-blue text-background';
      case 'completed': return 'bg-green-500 text-background';
      case 'pending': return 'bg-yellow-500 text-background';
      default: return 'bg-secondary';
    }
  };

  const getTypeLabel = (type: string) => {
    switch (type) {
      case 'fs22-mod': return 'FS22 Mod';
      case 'fs25-mod': return 'FS25 Mod';
      case 'api-integration': return 'API';
      case 'automation': return 'Automation';
      default: return type;
    }
  };

  return (
    <Card className="bg-card/50 backdrop-blur-sm border-border h-full">
      <CardHeader>
        <CardTitle className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <FolderOpen className="h-5 w-5 text-cyber-blue" />
            <span className="text-cyber-blue">Project Manager</span>
          </div>
          <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
            <DialogTrigger asChild>
              <Button size="sm" className="bg-cyber-blue hover:bg-cyber-blue-dark">
                <Plus className="h-4 w-4 mr-2" />
                New Project
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Create New Project</DialogTitle>
              </DialogHeader>
              <div className="space-y-4">
                <div>
                  <Label htmlFor="project-name">Project Name</Label>
                  <Input
                    id="project-name"
                    value={newProject.name}
                    onChange={(e) => setNewProject(prev => ({ ...prev, name: e.target.value }))}
                    placeholder="Enter project name..."
                  />
                </div>
                <div>
                  <Label htmlFor="project-type">Project Type</Label>
                  <Select value={newProject.type} onValueChange={(value) => setNewProject(prev => ({ ...prev, type: value as Project['type'] }))}>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="fs22-mod">FS22 Mod</SelectItem>
                      <SelectItem value="fs25-mod">FS25 Mod</SelectItem>
                      <SelectItem value="api-integration">API Integration</SelectItem>
                      <SelectItem value="automation">Automation</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="flex space-x-2">
                  <Button variant="outline" onClick={() => setDialogOpen(false)}>
                    Cancel
                  </Button>
                  <Button onClick={handleCreateProject}>
                    Create Project
                  </Button>
                </div>
              </div>
            </DialogContent>
          </Dialog>
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        {loading ? (
          <div className="flex items-center justify-center py-8">
            <Loader2 className="h-8 w-8 animate-spin text-primary" />
            <span className="ml-2 text-muted-foreground">Loading projects...</span>
          </div>
        ) : projects.length === 0 ? (
          <div className="text-center py-8 text-muted-foreground">
            <FolderOpen className="h-12 w-12 mx-auto mb-4 opacity-50" />
            <p>No projects created yet</p>
            <p className="text-sm">Click "New Project" to get started</p>
          </div>
        ) : (
          projects.map((project) => (
            <div key={project.id} className="p-4 rounded-lg bg-secondary/50 border border-border">
              <div className="flex items-center justify-between mb-2">
                <h3 className="font-semibold text-foreground">{project.name}</h3>
                <div className="flex space-x-2">
                  <Badge variant="secondary" className="bg-tech-gray-light">
                    {getTypeLabel(project.type)}
                  </Badge>
                  <Badge className={getStatusColor(project.status)}>
                    <div className="flex items-center gap-1">
                      {project.status === 'active' && <Clock className="h-3 w-3" />}
                      {project.status === 'completed' && <CheckCircle className="h-3 w-3" />}
                      {project.status === 'pending' && <FolderOpen className="h-3 w-3" />}
                      {project.status}
                    </div>
                  </Badge>
                </div>
              </div>
              <div className="space-y-2">
                <div className="flex items-center justify-between text-sm">
                  <span className="text-muted-foreground">Progress</span>
                  <span className="text-cyber-blue font-medium">{project.progress}%</span>
                </div>
                <Progress value={project.progress} className="h-2" />
                <p className="text-xs text-muted-foreground">
                  Last updated: {project.lastUpdated.toLocaleDateString()}
                </p>
              </div>
              <div className="flex space-x-2 mt-3">
                <Button variant="outline" size="sm" className="border-cyber-blue/20 text-cyber-blue hover:bg-cyber-blue/10">
                  <FolderOpen className="h-3 w-3 mr-1" />
                  View Details
                </Button>
                {project.status === 'active' && (
                  <Button variant="outline" size="sm" className="border-tech-accent/20 text-tech-accent hover:bg-tech-accent/10">
                    <Rocket className="h-3 w-3 mr-1" />
                    Deploy
                  </Button>
                )}
              </div>
            </div>
          ))
        )}
      </CardContent>
    </Card>
  );
}