import jsPDF from 'jspdf';

interface ChatMessage {
  role: string;
  content: string;
  timestamp?: string;
}

interface ChatPDFOptions {
  userId: string;
  conversationTitle: string;
  messages: ChatMessage[];
  aiSummary?: string;
}

/**
 * Generates a branded PDF from chat messages
 */
export async function generateChatPDF(options: ChatPDFOptions): Promise<string | null> {
  const { userId, conversationTitle, messages, aiSummary } = options;

  try {
    const pdf = new jsPDF();
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 20;
    let y = margin;

    // Add header with branding
    pdf.setFillColor(8, 31, 53); // #081F35
    pdf.rect(0, 0, pageWidth, 35, 'F');

    // Logo text (as fallback)
    pdf.setTextColor(216, 177, 66); // #D8B142
    pdf.setFontSize(20);
    pdf.setFont('helvetica', 'bold');
    pdf.text('CriderGPT', margin, 22);

    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text('Chat Export', pageWidth - margin, 18, { align: 'right' });
    pdf.text(new Date().toLocaleDateString(), pageWidth - margin, 26, { align: 'right' });

    y = 50;

    // Title
    pdf.setTextColor(8, 31, 53);
    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'bold');
    pdf.text(conversationTitle || 'Chat Conversation', margin, y);
    y += 10;

    // Metadata
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(100, 100, 100);
    pdf.text(`Messages: ${messages.length}`, margin, y);
    pdf.text(`Exported: ${new Date().toLocaleString()}`, pageWidth - margin, y, { align: 'right' });
    y += 15;

    // AI Summary if provided
    if (aiSummary) {
      pdf.setFillColor(248, 250, 252);
      pdf.roundedRect(margin, y, pageWidth - margin * 2, 30, 3, 3, 'F');
      
      pdf.setTextColor(8, 31, 53);
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Summary', margin + 5, y + 8);
      
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(9);
      const summaryLines = pdf.splitTextToSize(aiSummary, pageWidth - margin * 2 - 10);
      pdf.text(summaryLines.slice(0, 3), margin + 5, y + 16);
      y += 40;
    }

    // Separator
    pdf.setDrawColor(216, 177, 66);
    pdf.setLineWidth(0.5);
    pdf.line(margin, y, pageWidth - margin, y);
    y += 10;

    // Messages
    for (const msg of messages) {
      // Check if we need a new page
      if (y > pageHeight - 40) {
        pdf.addPage();
        y = margin;
        
        // Add header on new pages
        pdf.setFillColor(8, 31, 53);
        pdf.rect(0, 0, pageWidth, 20, 'F');
        pdf.setTextColor(216, 177, 66);
        pdf.setFontSize(12);
        pdf.text('CriderGPT Chat Export (continued)', margin, 13);
        y = 30;
      }

      // Role label
      const isUser = msg.role === 'user';
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(isUser ? 8 : 45, isUser ? 31 : 90, isUser ? 53 : 39);
      pdf.text(isUser ? '👤 You' : '🤖 CriderGPT', margin, y);
      
      // Timestamp if available
      if (msg.timestamp) {
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(8);
        pdf.setTextColor(150, 150, 150);
        const timeStr = new Date(msg.timestamp).toLocaleTimeString();
        pdf.text(timeStr, pageWidth - margin, y, { align: 'right' });
      }
      y += 6;

      // Message content
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(50, 50, 50);
      
      // Clean and wrap content
      const cleanContent = msg.content
        .replace(/\*\*/g, '')  // Remove markdown bold
        .replace(/\*/g, '')    // Remove markdown italic
        .replace(/`/g, '')     // Remove code ticks
        .replace(/#+\s/g, '')  // Remove headings
        .trim();
      
      const lines = pdf.splitTextToSize(cleanContent, pageWidth - margin * 2);
      const maxLines = 15; // Limit per message to prevent very long messages
      const displayLines = lines.slice(0, maxLines);
      
      for (const line of displayLines) {
        if (y > pageHeight - 30) {
          pdf.addPage();
          y = margin + 20;
        }
        pdf.text(line, margin, y);
        y += 5;
      }
      
      if (lines.length > maxLines) {
        pdf.setTextColor(150, 150, 150);
        pdf.setFontSize(8);
        pdf.text(`[... ${lines.length - maxLines} more lines]`, margin, y);
        y += 5;
      }

      y += 8; // Space between messages
    }

    // Footer on last page
    const addFooter = (pageNum: number, totalPages: number) => {
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text(
        `Page ${pageNum} of ${totalPages} | Generated by CriderGPT`,
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
      );
    };

    // Add footers to all pages
    const totalPages = pdf.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      addFooter(i, totalPages);
    }

    // Watermark
    pdf.setPage(1);
    pdf.setTextColor(200, 200, 200);
    pdf.setFontSize(60);
    pdf.setFont('helvetica', 'bold');
    pdf.text('CriderGPT', pageWidth / 2, pageHeight / 2, {
      align: 'center',
      angle: 45,
    });

    // Generate filename
    const safeName = (conversationTitle || 'chat')
      .replace(/[^a-zA-Z0-9]/g, '-')
      .substring(0, 30);
    const filename = `cridergpt-${safeName}-${Date.now()}.pdf`;

    // Save PDF
    pdf.save(filename);

    return filename;
  } catch (error) {
    console.error('Error generating chat PDF:', error);
    throw error;
  }
}

/**
 * Detects if a message is requesting PDF export
 */
export function isPDFRequest(message: string): boolean {
  const lowerMessage = message.toLowerCase();
  
  // Explicit PDF patterns
  const explicitPatterns = [
    /\b(export|save|download|convert|make|create|generate)\s+(this|chat|conversation|messages?)?\s*(as|to|into)?\s*(a\s+)?pdf\b/i,
    /\b(pdf|document)\s+(export|download|save|generate|create)\b/i,
    /\bpdf\s+(this|chat|conversation)\b/i,
    /\b(give|send|email)\s+me\s+(a\s+)?pdf\b/i,
    /\bexport\s+(to\s+)?document\b/i,
  ];

  // Action + context patterns
  const actionKeywords = /\b(export|generate|create|save|download|make|print)\b/i;
  const contextKeywords = /\b(pdf|document|doc|file|report|printable|summary)\b/i;

  // Check explicit patterns first
  for (const pattern of explicitPatterns) {
    if (pattern.test(message)) return true;
  }

  // Check action + context combination
  if (actionKeywords.test(message) && contextKeywords.test(message)) {
    return true;
  }

  return false;
}
