
import jsPDF from 'jspdf';

export interface InvoiceData {
  invoiceNumber: string;
  date: string;
  dueDate: string;
  billTo: {
    name: string;
    company: string;
    address: string;
    email: string;
  };
  items: Array<{
    description: string;
    quantity: number;
    rate: number;
    amount: number;
  }>;
  subtotal: number;
  tax: number;
  total: number;
  notes: string;
}

export function exportInvoiceToPDF(invoiceData: InvoiceData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  const margin = 20;
  let yPosition = 20;

  // CriderGPT Header with branding
  doc.setFontSize(28);
  doc.setTextColor(0, 102, 204);
  doc.text('CriderGPT', margin, yPosition);
  
  yPosition += 8;
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text('Professional Calculator Suite', margin, yPosition);
  
  // Invoice title
  yPosition += 20;
  doc.setFontSize(24);
  doc.setTextColor(0, 0, 0);
  doc.text('INVOICE', pageWidth - margin, yPosition, { align: 'right' });
  
  // Invoice details (top right)
  yPosition += 15;
  doc.setFontSize(10);
  doc.text(`Invoice #: ${invoiceData.invoiceNumber}`, pageWidth - margin, yPosition, { align: 'right' });
  
  yPosition += 8;
  doc.text(`Date: ${new Date(invoiceData.date).toLocaleDateString()}`, pageWidth - margin, yPosition, { align: 'right' });
  
  yPosition += 8;
  doc.text(`Due Date: ${new Date(invoiceData.dueDate).toLocaleDateString()}`, pageWidth - margin, yPosition, { align: 'right' });

  // Bill To section
  yPosition += 25;
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Bill To:', margin, yPosition);
  
  yPosition += 10;
  doc.setFontSize(12);
  doc.text(invoiceData.billTo.name, margin, yPosition);
  
  if (invoiceData.billTo.company) {
    yPosition += 8;
    doc.text(invoiceData.billTo.company, margin, yPosition);
  }
  
  if (invoiceData.billTo.address) {
    yPosition += 8;
    const addressLines = doc.splitTextToSize(invoiceData.billTo.address, 100);
    doc.text(addressLines, margin, yPosition);
    yPosition += addressLines.length * 5;
  }
  
  if (invoiceData.billTo.email) {
    yPosition += 8;
    doc.text(invoiceData.billTo.email, margin, yPosition);
  }

  // Items table
  yPosition += 30;
  const tableStartY = yPosition;
  
  // Table headers
  doc.setFontSize(10);
  doc.setFont(undefined, 'bold');
  doc.text('Description', margin, yPosition);
  doc.text('Qty', pageWidth - 120, yPosition, { align: 'right' });
  doc.text('Rate', pageWidth - 80, yPosition, { align: 'right' });
  doc.text('Amount', pageWidth - margin, yPosition, { align: 'right' });
  
  // Header line
  yPosition += 5;
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  
  // Items
  yPosition += 10;
  doc.setFont(undefined, 'normal');
  
  invoiceData.items.forEach((item) => {
    if (yPosition > pageHeight - 60) {
      doc.addPage();
      yPosition = 30;
    }
    
    const descriptionLines = doc.splitTextToSize(item.description, 120);
    doc.text(descriptionLines, margin, yPosition);
    doc.text(item.quantity.toString(), pageWidth - 120, yPosition, { align: 'right' });
    doc.text(formatCurrency(item.rate), pageWidth - 80, yPosition, { align: 'right' });
    doc.text(formatCurrency(item.amount), pageWidth - margin, yPosition, { align: 'right' });
    
    yPosition += Math.max(descriptionLines.length * 5, 8) + 5;
  });

  // Totals section
  yPosition += 10;
  doc.line(pageWidth - 100, yPosition, pageWidth - margin, yPosition);
  
  yPosition += 10;
  doc.text('Subtotal:', pageWidth - 100, yPosition);
  doc.text(formatCurrency(invoiceData.subtotal), pageWidth - margin, yPosition, { align: 'right' });
  
  yPosition += 8;
  doc.text('Tax:', pageWidth - 100, yPosition);
  doc.text(formatCurrency(invoiceData.tax), pageWidth - margin, yPosition, { align: 'right' });
  
  yPosition += 10;
  doc.setFont(undefined, 'bold');
  doc.text('Total:', pageWidth - 100, yPosition);
  doc.text(formatCurrency(invoiceData.total), pageWidth - margin, yPosition, { align: 'right' });
  
  // Notes section
  if (invoiceData.notes) {
    yPosition += 30;
    doc.setFont(undefined, 'bold');
    doc.text('Notes:', margin, yPosition);
    
    yPosition += 10;
    doc.setFont(undefined, 'normal');
    const noteLines = doc.splitTextToSize(invoiceData.notes, pageWidth - 2 * margin);
    doc.text(noteLines, margin, yPosition);
    yPosition += noteLines.length * 5;
  }

  // Footer with CriderGPT branding
  const footerY = pageHeight - 20;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by CriderGPT Professional Calculator Suite', pageWidth / 2, footerY, { align: 'center' });
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, pageWidth / 2, footerY + 5, { align: 'center' });

  // Generate filename
  const dateStr = new Date().toISOString().split('T')[0];
  const filename = `CriderGPT_Invoice_${invoiceData.invoiceNumber}_${dateStr}.pdf`;
  
  doc.save(filename);
}

function formatCurrency(value: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD'
  }).format(value);
}
