
INSERT INTO product_ideas (created_by, title, description, category, status, materials, est_cost, sell_price, notes, is_patented, is_public) VALUES
('51e55ded-3a0e-4d50-bc15-bb76b2712ba9', 'NFC Windshield Tag', 'A small NFC tag mounted inside the vehicle windshield. When scanned, it pulls up the vehicle''s full maintenance history, registration info, and owner details from the Smart ID system. Cheap to produce — just an NFC sticker + a weatherproof sleeve.', 'accessories', 'idea', '[{"name":"NFC 215 Stickers (50-pack)","cost":8.99,"bought":false},{"name":"Clear Weatherproof Sleeves (50-pack)","cost":5.50,"bought":false},{"name":"Custom QR/NFC Label Printing","cost":12.00,"bought":false}]'::jsonb, 1.50, 4.99, 'Connects directly to CriderGPT Smart ID system. Customer scans tag → sees vehicle profile. Could bundle with livestock tags for farm trucks. Step 1: Order NFC 215 stickers. Step 2: Program each with unique URL pointing to Smart ID profile. Step 3: Package in weatherproof sleeve. Step 4: List on store.', false, false),

('51e55ded-3a0e-4d50-bc15-bb76b2712ba9', 'Smart Toolbox Inventory Tag', 'NFC tag stuck inside toolbox lid. Scan it to see a digital checklist of all tools that should be in the box. Helps mechanics and farmers track missing tools. Links to Smart ID system for tool ownership proof.', 'accessories', 'idea', '[{"name":"NFC 215 Stickers (25-pack)","cost":4.99,"bought":false},{"name":"Heavy-duty adhesive pads","cost":3.50,"bought":false}]'::jsonb, 0.75, 3.50, 'Super cheap to make. Program each tag with a unique tool inventory list. Could sell to mechanics, welding shops, farm hands. Step 1: Buy NFC stickers. Step 2: Build tool checklist template in Smart ID. Step 3: Program tags. Step 4: Sell individually or in packs of 5.', false, false),

('51e55ded-3a0e-4d50-bc15-bb76b2712ba9', 'Vehicle OBD-II Smart Connector', 'A Bluetooth OBD-II reader paired with an NFC tag on the dash. Scan the NFC tag → it opens the vehicle profile AND pulls live diagnostics from the OBD reader via the app. Shows check engine codes, fuel economy, battery voltage.', 'electronics', 'researching', '[{"name":"ELM327 Bluetooth OBD-II Reader","cost":7.99,"bought":false},{"name":"NFC 215 Sticker","cost":0.25,"bought":false},{"name":"Custom branded case/sleeve","cost":2.00,"bought":false}]'::jsonb, 10.00, 24.99, 'Higher margin product. Buy cheap ELM327 readers in bulk from wholesale. Bundle with an NFC tag that links to the Smart ID vehicle profile. Step 1: Source ELM327 readers (AliExpress bulk). Step 2: Program NFC tags. Step 3: Create vehicle diagnostic view in CriderGPT. Step 4: Package and sell as a kit.', false, false),

('51e55ded-3a0e-4d50-bc15-bb76b2712ba9', 'Livestock Ear Tag + GPS Collar Bundle', 'Bundle the existing Smart NFC ear tag ($3.50) with a cheap GPS collar for cattle/goats. The ear tag handles ID and health records, the GPS collar handles location tracking. Both feed into the Smart ID dashboard.', 'livestock', 'idea', '[{"name":"Smart NFC Ear Tags (10-pack)","cost":35.00,"bought":false},{"name":"Mini GPS Tracker Collars (bulk 10)","cost":89.00,"bought":false},{"name":"Collar straps + buckles","cost":15.00,"bought":false}]'::jsonb, 14.00, 29.99, 'Premium bundle product. GPS trackers are cheap from wholesale. The real value is the Smart ID software integration that ties location + health records together. Step 1: Source GPS trackers. Step 2: Build GPS data integration in CriderGPT. Step 3: Bundle with existing ear tags. Step 4: Market to ranchers.', false, false),

('51e55ded-3a0e-4d50-bc15-bb76b2712ba9', 'Farm Equipment Key Tag', 'NFC tag attached to tractor/equipment keys. Scan to see equipment hours, last maintenance date, fuel logs, and operator assignments. Works with any farm equipment — tractors, ATVs, side-by-sides, welders.', 'accessories', 'idea', '[{"name":"NFC 215 Keychain Tags (25-pack)","cost":9.99,"bought":false},{"name":"Split rings + carabiners","cost":4.50,"bought":false}]'::jsonb, 0.85, 3.99, 'Very cheap to produce. Huge market — every farmer has multiple pieces of equipment. Step 1: Order NFC keychain tags. Step 2: Create equipment profile template in Smart ID. Step 3: Program tags. Step 4: Sell individually or in farm packs of 10.', false, false),

('51e55ded-3a0e-4d50-bc15-bb76b2712ba9', 'Pet Smart ID Tag', 'Waterproof NFC pet tag that clips to collar. When scanned by anyone (no app needed), shows pet name, owner contact info, vet records, vaccination dates. Emergency contact and lost pet alert built in.', 'accessories', 'idea', '[{"name":"Waterproof NFC Pet Tags (25-pack)","cost":14.99,"bought":false},{"name":"D-ring collar clips","cost":6.00,"bought":false},{"name":"Laser engraving (optional branding)","cost":8.00,"bought":false}]'::jsonb, 1.50, 5.99, 'Huge pet market. Works without any app — just tap with phone. Step 1: Source waterproof NFC pet tags. Step 2: Build pet profile template. Step 3: Program and engrave. Step 4: Sell on store + local pet shops. Could do custom engraving for extra $2.', false, false);
