-- Seed cridergpt_training_corpus with starter knowledge across 4 domains
-- Idempotent: only insert if topic doesn't already exist

INSERT INTO public.cridergpt_training_corpus (source_table, category, topic, content, metadata)
SELECT * FROM (VALUES
  -- ===== AGRICULTURE / FFA =====
  ('seed', 'agriculture', 'FFA Founding', 'The National FFA Organization was founded in 1928 in Kansas City, Missouri. Originally called Future Farmers of America, the name was changed in 1988 to the National FFA Organization to reflect the growing diversity of agriculture. The official colors are National Blue and Corn Gold.', '{"tags":["ffa","history"]}'::jsonb),
  ('seed', 'agriculture', 'FFA Creed', 'The FFA Creed was written by E.M. Tiffany and adopted at the 3rd National Convention in 1930. It has been revised twice — at the 38th Convention (1965) and the 63rd Convention (1990). It contains five paragraphs, each beginning with "I believe".', '{"tags":["ffa","creed"]}'::jsonb),
  ('seed', 'agriculture', 'SAE Programs', 'A Supervised Agricultural Experience (SAE) is a hands-on, student-led project in agriculture. Types include: Foundational SAE (career exploration, employability skills), Entrepreneurship, Placement/Internship, Research, and School-Based Enterprise.', '{"tags":["ffa","sae"]}'::jsonb),
  ('seed', 'agriculture', 'Soil pH for Crops', 'Most field crops thrive at soil pH 6.0–7.0. Corn prefers 6.0–6.8, soybeans 6.3–6.8, alfalfa 6.5–7.5, blueberries 4.5–5.5. Lime raises pH; elemental sulfur lowers it. Always soil-test before amending.', '{"tags":["soil","crops"]}'::jsonb),
  ('seed', 'agriculture', 'Cattle Gestation', 'Beef and dairy cattle gestation averages 283 days (about 9 months and 10 days). Breed variation: Angus ~283, Holstein ~279, Brahman ~292. Track breeding dates to plan calving and winter feed.', '{"tags":["livestock","cattle"]}'::jsonb),
  ('seed', 'agriculture', 'Hog Gestation', 'Swine gestation is the famous "3-3-3": 3 months, 3 weeks, 3 days — about 114 days. Sows typically farrow 8–12 piglets per litter.', '{"tags":["livestock","swine"]}'::jsonb),
  ('seed', 'agriculture', 'Sheep Gestation', 'Sheep gestation averages 147 days (about 5 months). Ewes commonly twin; triplets are not unusual in productive breeds like Polypay or Finnsheep.', '{"tags":["livestock","sheep"]}'::jsonb),
  ('seed', 'agriculture', 'Hay Moisture', 'Bale hay at 15–18% moisture for small squares, under 16% for large rounds, and under 14% for large squares. Above 20% risks mold and barn fires from spontaneous combustion.', '{"tags":["hay","forage"]}'::jsonb),
  ('seed', 'agriculture', 'Corn Planting Depth', 'Plant corn 1.5–2 inches deep in moist soil. Shallower in cool wet soil for faster emergence; deeper in dry conditions to reach moisture. Uniform depth = uniform emergence = higher yield.', '{"tags":["corn","planting"]}'::jsonb),
  ('seed', 'agriculture', 'NPK Basics', 'Nitrogen (N) drives leafy growth, Phosphorus (P) builds roots and energy transfer, Potassium (K) regulates water and disease resistance. A 10-10-10 fertilizer is balanced; soil tests tell you what you actually need.', '{"tags":["fertilizer","nutrients"]}'::jsonb),
  ('seed', 'agriculture', 'Crop Rotation', 'Rotate crops to break pest and disease cycles, manage nitrogen, and improve soil structure. Classic 3-year rotation: corn → soybeans → wheat. Legumes (soybeans, alfalfa) fix nitrogen for the following crop.', '{"tags":["rotation","soil-health"]}'::jsonb),
  ('seed', 'agriculture', 'Cattle Body Condition', 'Body Condition Score (BCS) for beef cattle runs 1–9. Target BCS 5–6 at calving for cows, 6–7 for heifers. Below 4 means underfed; above 7 risks calving difficulty.', '{"tags":["cattle","nutrition"]}'::jsonb),
  ('seed', 'agriculture', 'Grass-Legume Pasture', 'A productive pasture mix for the eastern US: 60% cool-season grass (orchardgrass or fescue) + 30% legume (red or white clover) + 10% other forbs. Legumes boost protein and fix nitrogen.', '{"tags":["pasture","forage"]}'::jsonb),
  ('seed', 'agriculture', 'Livestock Tagging', 'USDA requires official ID for interstate movement of breeding cattle, dairy, rodeo, and exhibition animals. Options include metal NUES tags, RFID 840 tags, brands, and tattoos. Plain-text or NDEF NFC tags can supplement on-farm tracking.', '{"tags":["livestock","tagging","compliance"]}'::jsonb),
  ('seed', 'agriculture', 'Calving Signs', 'Imminent calving signs: udder filling 2–4 weeks out, vulva relaxation 1–2 weeks, mucus discharge 24–48 hours, isolation behavior, restlessness. Stage 1 labor lasts 2–6 hours; Stage 2 (active) should finish within 1 hour.', '{"tags":["cattle","calving"]}'::jsonb),

  -- ===== MECHANICS =====
  ('seed', 'mechanics', 'Engine Stroke Cycle', 'A 4-stroke engine cycle: Intake (piston down, intake valve open), Compression (piston up, both valves closed), Power (combustion drives piston down), Exhaust (piston up, exhaust valve open). Crankshaft turns twice per cycle.', '{"tags":["engine","fundamentals"]}'::jsonb),
  ('seed', 'mechanics', 'Diesel vs Gas', 'Diesels compress air to ~16:1–22:1 and inject fuel into hot compressed air (compression ignition). Gas engines compress an air-fuel mix at ~8:1–12:1 and use a spark plug. Diesels make more torque, last longer, get better mileage; gas engines rev higher and run cleaner per dollar.', '{"tags":["engine","diesel","gas"]}'::jsonb),
  ('seed', 'mechanics', 'Hydraulic Basics', 'Hydraulic systems move force through pressurized fluid (Pascal''s law: pressure applied to a confined fluid transmits equally in all directions). Pressure × area = force. A 2000 PSI system on a 4 sq-in cylinder = 8000 lb of force.', '{"tags":["hydraulics","tractor"]}'::jsonb),
  ('seed', 'mechanics', 'PTO Speeds', 'Standard tractor PTO speeds: 540 RPM (older/light implements), 1000 RPM (heavy implements like big balers and silage choppers). Some tractors offer "economy" PTO at lower engine RPM for fuel savings. Always match implement to tractor PTO.', '{"tags":["tractor","pto"]}'::jsonb),
  ('seed', 'mechanics', 'Three-Point Hitch Categories', 'Cat 0 (sub-compact, ~20 hp), Cat 1 (compact, 20–45 hp), Cat 2 (utility, 40–100 hp), Cat 3 (large, 80–225 hp), Cat 4 (high-hp, 180+ hp). Pin diameters and spacing differ — check before buying implements.', '{"tags":["tractor","hitch"]}'::jsonb),
  ('seed', 'mechanics', 'Welding Basics', 'MIG (GMAW) — fast, easy, indoor work, uses shielding gas. TIG (GTAW) — precise, clean, slow, great for thin metal and aluminum. Stick (SMAW) — works outdoors and on dirty/rusty steel, no gas needed. Common rod for general repair: 6011 or 7018.', '{"tags":["welding","fab"]}'::jsonb),
  ('seed', 'mechanics', 'Torque vs HP', 'Torque is rotational force (lb-ft). Horsepower is the rate of doing work: HP = (Torque × RPM) / 5252. At 5252 RPM, torque and HP curves cross. Diesels make peak torque low; gas engines make peak HP high.', '{"tags":["engine","theory"]}'::jsonb),
  ('seed', 'mechanics', 'Oil Viscosity', '5W-30 means SAE 5 weight cold (W = winter), SAE 30 weight at operating temp. Lower first number = better cold-start flow. Synthetic flows better cold and resists heat breakdown longer than conventional.', '{"tags":["oil","maintenance"]}'::jsonb),
  ('seed', 'mechanics', 'Battery CCA', 'Cold Cranking Amps (CCA) = current a battery can deliver at 0°F for 30 seconds while staying above 7.2V. Pickup trucks typically need 600–800 CCA, large diesels 950+. Higher CCA helps cold starts but won''t fix a bad starter.', '{"tags":["electrical","battery"]}'::jsonb),
  ('seed', 'mechanics', 'Ohms Law', 'V = I × R. Volts = Amps × Ohms. To find current draw of a 12V load with 4 ohms resistance: I = 12 / 4 = 3 amps. Power: P = V × I, so that load draws 36 watts.', '{"tags":["electrical","theory"]}'::jsonb),
  ('seed', 'mechanics', 'Fuse Sizing', 'Size automotive fuses at 125–150% of expected continuous current. A 10A continuous load = 15A fuse. Wire gauge must handle the fuse rating: 14 AWG good to 15A, 12 AWG to 20A, 10 AWG to 30A.', '{"tags":["electrical","wiring"]}'::jsonb),
  ('seed', 'mechanics', 'Bearing Failures', 'Common bearing failure modes: spalling (surface fatigue from overload), brinelling (dents from impact or static load), false brinelling (vibration in storage), contamination (dirt/water), and lack of lubrication (the #1 killer).', '{"tags":["bearings","maintenance"]}'::jsonb),
  ('seed', 'mechanics', 'V-Belt Tension', 'Properly tensioned V-belt deflects 1/64 inch per inch of span at the midpoint with moderate thumb pressure. Loose belts slip and burn; over-tight belts wear bearings and shafts.', '{"tags":["belts","drive"]}'::jsonb),
  ('seed', 'mechanics', 'Greasing Schedules', 'Rule of thumb: grease pivot points and U-joints every 8–10 operating hours, more often in dust or mud. Wheel bearings: repack annually or per OEM. Use NLGI #2 lithium complex for most farm and auto applications.', '{"tags":["maintenance","grease"]}'::jsonb),
  ('seed', 'mechanics', 'Coolant Mix', 'Standard 50/50 antifreeze + distilled water protects to about -34°F and raises boiling point to ~265°F (with 15 PSI cap). Never use straight antifreeze — water carries heat better than glycol.', '{"tags":["cooling","coolant"]}'::jsonb),

  -- ===== CODING =====
  ('seed', 'coding', 'TypeScript Basics', 'TypeScript adds static types to JavaScript. Types are erased at compile time — runtime is plain JS. Common primitives: string, number, boolean, null, undefined, bigint, symbol. Use "interface" for object shapes, "type" for unions and aliases.', '{"tags":["typescript","fundamentals"]}'::jsonb),
  ('seed', 'coding', 'React useState', 'useState returns [value, setter]. Setter calls trigger re-render. To update from previous: setCount(c => c + 1). Never mutate state directly — always return a new object/array.', '{"tags":["react","hooks"]}'::jsonb),
  ('seed', 'coding', 'React useEffect', 'useEffect(fn, deps) runs after render. Empty deps [] = run once on mount. Missing deps array = run every render. Return a cleanup function for subscriptions/timers. Don''t put async directly inside — wrap in an inner async function.', '{"tags":["react","hooks"]}'::jsonb),
  ('seed', 'coding', 'Supabase Auth', 'Supabase auth uses JWTs. supabase.auth.getUser() fetches current user; supabase.auth.signInWithPassword(), signInWithOAuth(), signOut() handle sessions. Listen to auth changes with supabase.auth.onAuthStateChange().', '{"tags":["supabase","auth"]}'::jsonb),
  ('seed', 'coding', 'Supabase RLS', 'Row Level Security policies are SQL conditions enforced per row. Always enable RLS on tables with user data: ALTER TABLE x ENABLE ROW LEVEL SECURITY. Policies typically check auth.uid() = user_id.', '{"tags":["supabase","security"]}'::jsonb),
  ('seed', 'coding', 'Edge Function CORS', 'Deno edge functions need CORS headers for browser calls: Access-Control-Allow-Origin, Allow-Headers (authorization, content-type, apikey, x-client-info). Always handle OPTIONS preflight requests.', '{"tags":["deno","cors"]}'::jsonb),
  ('seed', 'coding', 'Async Await', 'async functions return Promises. await pauses until the Promise resolves. Wrap awaits in try/catch for error handling. Run independent awaits in parallel with Promise.all([a, b]) — don''t await sequentially.', '{"tags":["javascript","async"]}'::jsonb),
  ('seed', 'coding', 'Git Basics', 'git status (see changes), git add (stage), git commit -m "msg" (record), git push (upload). Branch with git checkout -b feature, merge with git merge feature. Always pull before push to avoid conflicts.', '{"tags":["git","workflow"]}'::jsonb),
  ('seed', 'coding', 'REST vs GraphQL', 'REST: many endpoints, fixed shape, easy caching. GraphQL: one endpoint, client picks fields, fewer round trips, harder caching. Pick REST for simple CRUD; GraphQL for complex nested data and many clients.', '{"tags":["api","architecture"]}'::jsonb),
  ('seed', 'coding', 'Tailwind Utility', 'Tailwind is utility-first: compose styles inline with classes (bg-blue-500, p-4, flex). Use semantic tokens via CSS variables for themability. Responsive: sm:, md:, lg:, xl: prefixes. Dark mode: dark: prefix.', '{"tags":["tailwind","css"]}'::jsonb),
  ('seed', 'coding', 'Python List Comprehension', '[x*2 for x in nums if x > 0] is faster and more readable than a for-loop with append. Dict comprehension: {k: v*2 for k, v in d.items()}. Generator: (x*2 for x in nums) — lazy, memory-efficient.', '{"tags":["python","syntax"]}'::jsonb),
  ('seed', 'coding', 'SQL Joins', 'INNER JOIN: only matching rows. LEFT JOIN: all left rows + matching right (NULL if none). RIGHT JOIN: opposite. FULL OUTER: all rows from both. CROSS JOIN: cartesian product (rare, careful).', '{"tags":["sql","joins"]}'::jsonb),
  ('seed', 'coding', 'Database Indexing', 'Indexes speed up reads but slow writes. Index columns used in WHERE, JOIN, ORDER BY. Composite index column order matters — leftmost prefix rule. Don''t over-index small tables.', '{"tags":["sql","performance"]}'::jsonb),
  ('seed', 'coding', 'JWT Tokens', 'JWT = JSON Web Token. Three base64 parts separated by dots: header.payload.signature. Payload is readable — never put secrets in it. Verify signature server-side before trusting claims.', '{"tags":["auth","security"]}'::jsonb),
  ('seed', 'coding', 'Docker Basics', 'Docker packages an app + dependencies into a container image. Dockerfile defines the image. docker build -t name . then docker run name. docker-compose orchestrates multi-container apps via a YAML file.', '{"tags":["docker","devops"]}'::jsonb),
  ('seed', 'coding', 'API Rate Limits', 'Rate limits are usually expressed as N requests per window (e.g., 60/minute). Common patterns: token bucket, sliding window, fixed window. Always handle 429 responses with exponential backoff.', '{"tags":["api","reliability"]}'::jsonb),
  ('seed', 'coding', 'Environment Variables', 'Store secrets in env vars, never in code or git. Vite exposes only VITE_ prefixed vars to the browser. Server-side secrets go in edge function env or hosting provider secret stores.', '{"tags":["security","config"]}'::jsonb),

  -- ===== TECH =====
  ('seed', 'tech', 'TCP vs UDP', 'TCP: connection-based, reliable, ordered, slower (web, email, file transfer). UDP: connectionless, fast, no guarantees (video calls, gaming, DNS). Pick TCP for correctness, UDP for speed and tolerance to loss.', '{"tags":["networking","protocols"]}'::jsonb),
  ('seed', 'tech', 'HTTP Status Codes', '2xx success (200 OK, 201 Created, 204 No Content). 3xx redirect (301 permanent, 302 temp). 4xx client error (400 bad request, 401 unauth, 403 forbidden, 404 not found, 429 rate limited). 5xx server error (500 internal, 502 bad gateway, 503 unavailable).', '{"tags":["http","web"]}'::jsonb),
  ('seed', 'tech', 'DNS Records', 'A record → IPv4 address. AAAA → IPv6. CNAME → alias to another domain. MX → mail server. TXT → arbitrary text (often SPF, DKIM, domain verification). NS → name servers for the zone.', '{"tags":["dns","networking"]}'::jsonb),
  ('seed', 'tech', 'HTTPS / TLS', 'HTTPS = HTTP over TLS. TLS encrypts traffic, authenticates the server via a certificate, and ensures integrity. Modern web requires HTTPS for HTTP/2, service workers, geolocation, camera/mic access.', '{"tags":["security","web"]}'::jsonb),
  ('seed', 'tech', 'CPU Cores vs Threads', 'A core is a physical processor; a thread is a unit of execution. Hyperthreading lets one core run 2 threads concurrently. A 4-core/8-thread CPU runs 8 threads at once but only 4 truly in parallel.', '{"tags":["hardware","cpu"]}'::jsonb),
  ('seed', 'tech', 'RAM vs Storage', 'RAM is fast volatile memory the CPU works in (lost on power-off). Storage (SSD/HDD) is slow non-volatile. NVMe SSDs ~3500 MB/s, SATA SSDs ~550 MB/s, HDDs ~150 MB/s, DDR4 RAM ~25,000 MB/s.', '{"tags":["hardware","memory"]}'::jsonb),
  ('seed', 'tech', 'GPU Compute', 'GPUs have thousands of small cores optimized for parallel math (matrix ops, graphics, AI training). NVIDIA dominates AI via CUDA. AMD GPUs use ROCm. Apple Silicon uses Metal. Most ML frameworks need NVIDIA for best performance.', '{"tags":["hardware","gpu","ai"]}'::jsonb),
  ('seed', 'tech', 'IPv4 vs IPv6', 'IPv4: 32-bit, ~4.3 billion addresses, exhausted, uses NAT. IPv6: 128-bit, effectively infinite, no NAT needed. IPv6 addresses look like 2001:db8::1. Both still coexist; most networks dual-stack.', '{"tags":["networking","ip"]}'::jsonb),
  ('seed', 'tech', 'Linux vs Windows', 'Linux is open-source, free, dominates servers and embedded systems, uses bash/zsh. Windows is proprietary, dominates desktop and gaming. macOS is BSD-based Unix with Apple polish. WSL runs Linux inside Windows.', '{"tags":["os","platforms"]}'::jsonb),
  ('seed', 'tech', 'SSH Keys', 'SSH key auth replaces passwords. ssh-keygen creates a keypair (private stays on your machine, public goes on the server in ~/.ssh/authorized_keys). Use ed25519 or RSA 4096. Protect private key with a passphrase.', '{"tags":["security","ssh"]}'::jsonb),
  ('seed', 'tech', 'VPN Basics', 'A VPN tunnels your traffic through a remote server, hiding your IP and encrypting on untrusted networks. WireGuard is modern/fast; OpenVPN is older/compatible. Self-hosting: WireGuard on a $5 VPS works great.', '{"tags":["networking","privacy"]}'::jsonb),
  ('seed', 'tech', 'Cloud vs On-Prem', 'Cloud: rent compute, scale instantly, pay for use, no hardware. On-prem: own hardware, fixed cost, full control, higher latency to manage. Hybrid is common — sensitive data on-prem, scalable workloads in cloud.', '{"tags":["cloud","infrastructure"]}'::jsonb),
  ('seed', 'tech', 'AI Inference vs Training', 'Training: feed data to adjust model weights — slow, expensive, GPU-heavy. Inference: run a trained model to get predictions — much cheaper, often runs on CPU. Most production AI is inference; fine-tuning is mid-cost training.', '{"tags":["ai","ml"]}'::jsonb),
  ('seed', 'tech', 'RAG Pattern', 'Retrieval-Augmented Generation: before asking an LLM, retrieve relevant docs from your own database and inject them into the prompt. Makes the model answer from your data, not just its training. Cheap way to "customize" without fine-tuning.', '{"tags":["ai","rag"]}'::jsonb),
  ('seed', 'tech', 'Embedding Vectors', 'Embeddings turn text into numeric vectors so similar meanings have similar vectors. Used for semantic search, clustering, RAG. Typical dim: 384–1536. Compare with cosine similarity.', '{"tags":["ai","embeddings"]}'::jsonb),
  ('seed', 'tech', 'WebSocket vs HTTP', 'HTTP is request-response, one-shot. WebSocket opens a persistent bidirectional channel — server can push to client without polling. Use for chat, live data, multiplayer games. Falls back to long-polling on restrictive networks.', '{"tags":["web","realtime"]}'::jsonb),
  ('seed', 'tech', 'OAuth Flow', 'OAuth 2.0 lets users grant your app limited access without sharing passwords. Authorization code flow: redirect to provider → user approves → provider redirects back with code → your server exchanges code for token. PKCE adds security for public clients.', '{"tags":["auth","oauth"]}'::jsonb),
  ('seed', 'tech', 'Webhooks', 'A webhook is an HTTP POST your server receives when an event happens elsewhere (Stripe payment, GitHub push). Always verify webhook signatures and respond fast (2xx within seconds), processing async if needed.', '{"tags":["api","integration"]}'::jsonb)
) AS v(source_table, category, topic, content, metadata)
WHERE NOT EXISTS (
  SELECT 1 FROM public.cridergpt_training_corpus t
  WHERE t.topic = v.topic AND t.source_table = 'seed'
);

CREATE INDEX IF NOT EXISTS idx_training_corpus_category ON public.cridergpt_training_corpus(category);
CREATE INDEX IF NOT EXISTS idx_training_corpus_topic ON public.cridergpt_training_corpus(topic);