import { useRef, useState } from "react";
import { DevHubPage } from "./_layout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Flame, Download } from "lucide-react";
import { toast } from "sonner";

export default function LaserStudio() {
  const [svgText, setSvgText] = useState("");
  const [power, setPower] = useState(80);
  const [speed, setSpeed] = useState(1500);
  const [feed, setFeed] = useState(3000);
  const previewRef = useRef<HTMLDivElement>(null);

  const onFile = async (f?: File) => {
    if (!f) return;
    const text = await f.text();
    setSvgText(text);
    if (previewRef.current) previewRef.current.innerHTML = text;
  };

  const toGcode = () => {
    if (!svgText) { toast.error("Upload an SVG first"); return; }
    // Very basic G-code stub from path d=... — for real engraving, run through svg2gcode locally.
    const parser = new DOMParser();
    const doc = parser.parseFromString(svgText, "image/svg+xml");
    const paths = Array.from(doc.querySelectorAll("path"));
    const lines: string[] = [
      "; Generated by CriderGPT Laser Studio",
      `; Power=${power}% Speed=${speed} Feed=${feed}`,
      "G21 ; mm", "G90 ; absolute", "M5 ; laser off",
      `G0 F${feed}`,
    ];
    paths.forEach((p, i) => {
      lines.push(`; --- path ${i} ---`);
      lines.push(`M3 S${Math.round(power * 10)}`);
      lines.push(`G1 F${speed}`);
      lines.push("; (insert linearized path here — pair with svg2gcode for full output)");
      lines.push("M5");
    });
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = "engraving.gcode"; a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <DevHubPage title="Laser Engraver Studio" subtitle="SVG → preview → G-code with your power/speed presets">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <Card>
          <CardHeader><CardTitle className="text-base flex items-center gap-2"><Flame className="w-4 h-4" /> Settings</CardTitle></CardHeader>
          <CardContent className="space-y-3">
            <div>
              <Label>SVG File</Label>
              <Input type="file" accept=".svg,image/svg+xml" onChange={(e) => onFile(e.target.files?.[0])} />
            </div>
            <div className="grid grid-cols-3 gap-2">
              <div><Label>Power %</Label><Input type="number" value={power} onChange={e => setPower(+e.target.value)} /></div>
              <div><Label>Speed</Label><Input type="number" value={speed} onChange={e => setSpeed(+e.target.value)} /></div>
              <div><Label>Feed</Label><Input type="number" value={feed} onChange={e => setFeed(+e.target.value)} /></div>
            </div>
            <Button onClick={toGcode} className="w-full"><Download className="w-4 h-4 mr-2" /> Export G-code</Button>
            <p className="text-[10px] text-muted-foreground">Stub G-code includes header + per-path scaffold. Pair with svg2gcode locally for full path rasterization.</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader><CardTitle className="text-base">Preview</CardTitle></CardHeader>
          <CardContent>
            <div ref={previewRef} className="bg-white rounded p-4 min-h-[300px] flex items-center justify-center text-muted-foreground">
              {!svgText && "SVG preview"}
            </div>
          </CardContent>
        </Card>
      </div>
    </DevHubPage>
  );
}
